name: Integration Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Exécuter tous les jours à minuit
  workflow_dispatch:
    inputs:
      php-version:
        description: "PHP version"
        required: true
        default: "8.4"
        type: choice
        options:
          - "8.4"
          - "8.3"
          - "8.2"
      symfony-version:
        description: "Symfony version"
        required: true
        default: "7.2"
        type: choice
        options:
          - "next"
          - "7.2"
          - "6.4"

permissions:
  contents: read

jobs:
  install:
    name: "PHP ${{ matrix.php-version }} / SF ${{ matrix.symfony-version }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - 
            php-version: 8.2
            symfony-version: 6.4
          - 
            php-version: 8.4
            symfony-version: 7.2
          - name: "PHP 8.4 / SF 7.3"
            php-version: 8.4
            symfony-version: "next"

    steps:
      - run: echo "${{ matrix.name }}"

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer, symfony
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }} # Add this line
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Create Symfony App
        run: |
          symfony new --webapp app --version="${{ matrix.symfony-version }}" --no-interaction
          cd app

      - name: Install MinifyBundle
        run: |
          cd app
          composer config extra.symfony.allow-contrib true
          composer config repositories.minify-bundle path ../../
          composer require sensiolabs/minify-bundle:@dev --no-interaction
          composer show sensiolabs/minify-bundle
          php bin/console debug:config sensiolabs_minify

      - name: Require assets
        run: |
          cd app
          mkdir -p assets/css assets/js
          php bin/console importmap:require bootstrap
          echo "  /** CSS */  body {  background-color:   red;  } " > assets/css/style.css
          echo " /** JS */ console.log('Hello' + 'world!  '  ); " > assets/js/script.js

      - name: Compile assets
        run: |
          cd app
          echo "## asset-map:compile "
          php bin/console asset-map:compile
          echo "========== /public =========="
          du -ha public

      - name: Generate Assets Comparison Table
        run: |
          cd app

          # Check if manifest file exists
          if [ ! -f public/assets/manifest.json ]; then
            echo "Manifest file not found!" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          # Write the table header
          echo "## Assets Comparison Table" >> $GITHUB_STEP_SUMMARY
          echo "| Source File                   | Source Size | Destination File                  | Dest Size  |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------------------------|-------------|----------------------------------|------------|" >> $GITHUB_STEP_SUMMARY

          # Parse the manifest.json and generate rows
          jq -r 'to_entries[] | "\(.key) \(.value)"' public/assets/manifest.json | while read -r source dest; do
            if [ -f "$source" ] && [ -f "$dest" ]; then
              source_size=$(ls -lh "$source" | awk '{print $5}')
              dest_size=$(ls -lh "$dest" | awk '{print $5}')
              printf "| %-30s | %-11s | %-32s | %-10s |\n" "$source" "$source_size" "$dest" "$dest_size" >> $GITHUB_STEP_SUMMARY
            fi
          done

      - name: Minify commands
        run: |
          cd app
          echo "## minify:install "
          php bin/console minify:install
          echo "## minify:asset "
          php bin/console minify:asset assets/css/style.css assets/css/style.min.css
          php bin/console minify:asset assets/js/script.js assets/js/script.min.js
          echo "========== /assets =========="
          du -ha assets

      - name: Generate Assets Comparison Summary
        run: |
          # Changer de répertoire vers 'app'
          cd app

          # Function to list files with sizes
          list_files_with_sizes() {
            local dir=$1
            if [ -d "$dir" ]; then
              find "$dir" -type f -exec ls -lh {} + | awk '{printf "| %-7s | %s |\n", $5, $9}'
            else
              echo "| N/A     | Directory $dir not found |"
            fi
          }

          # Write header for Markdown table
          echo "## Assets File Comparison" >> $GITHUB_STEP_SUMMARY

          # Add source (assets) files
          echo "### Source Files (assets)" >> $GITHUB_STEP_SUMMARY
          echo "| Size    | File Path                     |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|-------------------------------|" >> $GITHUB_STEP_SUMMARY
          list_files_with_sizes "assets" >> $GITHUB_STEP_SUMMARY

          # Add destination (public/assets) files
          echo "### Destination Files (public/assets)" >> $GITHUB_STEP_SUMMARY
          echo "| Size    | File Path                     |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|-------------------------------|" >> $GITHUB_STEP_SUMMARY
          list_files_with_sizes "public/assets" >> $GITHUB_STEP_SUMMARY
