name: Integration Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "PHP 8.2 + SF 6.4"
            php-version: 8.2
            symfony-version: 6.4
          - name: "PHP 8.3 + SF 7.2"
            php-version: 8.3
            symfony-version: 7.2
          - name: "PHP 8.4 + SF 7.3-dev"
            php-version: 8.4
            symfony-version: 7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer, symfony
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Composer: cache config"
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: "Composer: cache restore"
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Display Job Info
        run: echo "${{ matrix.name }}"

      - name: Create Symfony App
        run: |
          symfony new --webapp app --version="${{ matrix.symfony-version }}" --no-interaction
          cd app
          composer require sensiolabs/minify-bundle --dev

      - name: Compile assets
        run: |
          cd app
          php bin/console assets:install
          php bin/console cache:clear
          php bin/console cache:warmup
